In [2]:
#Gram Schmidt Orthogonalization
import numpy as np
def gram_schmidt(vectors):
    orthogonal_vectors = []
    for v in vectors:
        w = v - sum(np.dot(v, u) * u for u in orthogonal_vectors)
        orthogonal_vectors.append(w / np.linalg.norm(w))
    return np.array(orthogonal_vectors)

# Example: set of vectors
vectors = np.array([
    [1, 1, 1, 1],
    [1, 2, 4, 5],
    [1, -3, 4, -2]
 ])
 
# Applying Gram-Schmidt Orthogonalization
orthogonal_vectors = gram_schmidt(vectors)
print("Orthogonal Vectors:\n", orthogonal_vectors)

Orthogonal Vectors:
 [[ 0.5         0.5         0.5         0.5       ]
 [-0.63245553 -0.31622777  0.31622777  0.63245553]
 [ 0.21945509 -0.53034979  0.71322903 -0.40233433]]


In [3]:
#Least Square Method
import numpy as np
 
# Example matrix A and vector b
A = np.array([[1, 0], [1, 1], [1, 2], [1, 3]])
b = np.array([-1, 3, 5, 7])
 
# Solve using least squares method
x, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)
print("Solution x:", x)
E = A@x - b
E1 = 0
for i in E:
    E1 += i**2
print("Least Squared error:",E1**(1/2))

Solution x: [-0.4  2.6]
Least Squared error: 1.0954451150103324


In [4]:
#QR factorization
import numpy as np

# Example matrix A
A = np.array([[2, 3], [2, 4], [1, 1]])
b = np.array([7,3,1])
 
# QR Factorization
Q, R = np.linalg.qr(A)
print("Q:\n", Q)
print("R:\n", R)
X = np.linalg.inv(R)@(Q.T@b)
print("X:",X)

Q:
 [[-0.66666667  0.33333333]
 [-0.66666667 -0.66666667]
 [-0.33333333  0.66666667]]
R:
 [[-3. -5.]
 [ 0. -1.]]
X: [ 4. -1.]


In [6]:
#Cayley Hamilton Theorem
import numpy as np
from numpy.linalg import matrix_power

# Example matrix A
A = np.array([[4, 6, 6],[1, 3, 2],[-1, -4, -3]])
 
# Finding integer power using Cayley-Hamilton Theorem
def cayley_hamilton(A, n):
    # Compute the characteristic polynomial coefficients
    coeffs = np.poly(A)
    # Create the identity matrix
    I = np.eye(A.shape[0])
    # Compute A^n
    An = matrix_power(A, n)
    return An
    
n = -2  # example power
An = cayley_hamilton(A, n)
print(f"A^{n}:\n", An)

A^-2:
 [[ 0.0625 -1.125  -1.125 ]
 [-0.3125  0.625  -0.375 ]
 [ 0.3125  0.375   1.375 ]]


In [8]:
#Characteristic,Minimal polynomial and Jordan canonicaln Form
import numpy as np
from sympy import Matrix, symbols, lcm
 
# Define the matrix A
A = np.array([[3, 1, 0, 0],
              [1, 3, 0, 0],
              [0, 0, 3, 0],
              [0, 0, 0, 3]])
 
# Convert A to a SymPy Matrix for symbolic computation
A_sympy = Matrix(A)

# Symbolic variable for lambda
lamda = symbols('lamda')

# Find characteristic polynomial
char_poly = A_sympy.charpoly(lamda)
print(f"Characteristic Polynomial: {char_poly}")

# Find roots of the characteristic polynomial
char_roots = char_poly.all_roots()
print(f"All roots of the characteristic polynomial: {char_roots}")

# Function to calculate minimal polynomial from given roots
def calculate_minimal_polynomial(roots):
    minimal_poly = 1
    for root in set(roots):  # Use set to handle repeated roots
        minimal_poly *= (lamda - root)**roots.count(root)
    return minimal_poly.expand()

# Calculate minimal polynomial
min_poly = calculate_minimal_polynomial(char_roots)
print(f"Minimal Polynomial: {min_poly}")

Characteristic Polynomial: PurePoly(lamda**4 - 12*lamda**3 + 53*lamda**2 - 102*lamda + 72, lamda, domain='ZZ')
All roots of the characteristic polynomial: [2, 3, 3, 4]
Minimal Polynomial: lamda**4 - 12*lamda**3 + 53*lamda**2 - 102*lamda + 72


In [7]:
#Diagonalization of Matrices
 
import numpy as np

# Example matrix A
A = np.array([[1, 3, 3], [-3, -5, -3], [3, 3, 1]])

# Eigenvalues and eigenvectors of A
eigenvalues, eigenvectors = np.linalg.eig(A)

# Ensure eigenvalues and eigenvectors are sorted consistently
idx = np.argsort(eigenvalues)
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]

# Diagonal matrix D with eigenvalues
D = np.diag(eigenvalues)
 
print("Diagonal matrix D:\n", D)
print("Modal matrix P (eigenvectors):\n", eigenvectors)


Diagonal matrix D:
 [[-2.  0.  0.]
 [ 0. -2.  0.]
 [ 0.  0.  1.]]
Modal matrix P (eigenvectors):
 [[-1.28197512e-16 -6.72654054e-01  5.77350269e-01]
 [-7.07106781e-01  7.37141689e-01 -5.77350269e-01]
 [ 7.07106781e-01 -6.44876349e-02  5.77350269e-01]]


In [8]:
#Quadratic Form to Canonical Form
import numpy as np
from scipy.linalg import eigh

# Example matrix A (symmetric matrix)
A = np.array([[1, 0, 0], [0, 3, -1], [0, -1, 3]])

# Eigenvalues and eigenvectors for symmetric matrix
eigenvalues, eigenvectors = eigh(A)

# Canonical form
canonical_form = np.diag(eigenvalues)
print("Canonical form:\n", canonical_form)
print("Orthogonal matrix Q:\n", eigenvectors)

Canonical form:
 [[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 4.]]
Orthogonal matrix Q:
 [[ 1.          0.          0.        ]
 [ 0.          0.70710678 -0.70710678]
 [ 0.          0.70710678  0.70710678]]


In [9]:
#Singular value decomposition
import numpy as np

# Example matrix A
A = np.array([[-1, 1, 0], [0, -1, 1]])
 
# Singular Value Decomposition
U, S, Vt = np.linalg.svd(A)
print("U:\n", U)
print("S:\n", S)
print("Vt:\n", Vt)

U:
 [[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
S:
 [1.73205081 1.        ]
Vt:
 [[ 4.08248290e-01 -8.16496581e-01  4.08248290e-01]
 [-7.07106781e-01 -2.78976253e-16  7.07106781e-01]
 [ 5.77350269e-01  5.77350269e-01  5.77350269e-01]]


In [9]:
#Principle Component Analysis
import numpy as np
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
 
# Example data
# Assume data is a matrix where each row is a sample and each column is a feature
data = np.array([[4, 11],
                 [8, 4],
                 [13, 5],
                 [7, 14]])
 
# Centering the data
data_centered = data - np.mean(data, axis=0)
 
# Perform PCA
pca = PCA(n_components=1)
pca.fit(data_centered)

# Transform the data
transformed_data = pca.transform(data_centered)
 
# PCA components and explained variance
print("Principal components:\n", pca.components_)
print("Explained variance:", pca.explained_variance_ratio_)
first_pc = pca.components_@data_centered.T
print("First principal components:",first_pc)


Principal components:
 [[-0.55738997  0.83025082]]
Explained variance: [0.82121255]
First principal components: [[ 4.30518692 -3.73612869 -5.69282771  5.12376947]]
